language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  - provider: firebase
    project: dev
    token:
      secure: "u251apbKvwSFR4t6mhZAq18GIiuBc9+kbozgmS3oSu6VJSf50KTbzeQ/1qv6gKDIZE74fGuASICCBG0VFqlUVh0Be7vqoP5SPPmX1JxPrXWedXzTYOa2iPUcIUY21hPWt3ps2MAsNfPCMWcEzm+1WZlOHXDpix3QSRPpTdcyc8l2V1aOPQ/3eM5Qq1iqMO+giZGNkinChGDUEJDuAObGhg0s6vsPof/Sn8cFdVw0G3Wydq7CLLQvmPWVfltTOEy1Cb8uDxX+yDKA9XFPaD24jfp76BiO/qsgySd9QUvaf2vOfymTI1rpKJxG2p5LwvNkzbX99THeOdLs5YRFbNxqVzx7sVFfhmPAaibL0pk/znQL88hMCaJ/ww3UfYsF2e6TT3U32JhmYOQZX5BQBDzx7HxzyRJW2gq0JQJmNmOc7edOfiZOE7syHrqoVcb9cdEYe0/AJPP6sWR3b+l1ty2V8W2QPrEoxtSORxYk57JvvdhU0eLTFtwWlcMqTU90FYHOy6SvB5KmC1EXhDd5Pd/ayasLNUVaUpfzxNP/d2GnX97BhYHDMcO+SZ0mh5qqtXd+DTqkWqX+qtuKOQv202uH4QGV46RZ6PDPmnjZEmR7WPLXdvEvoH6pNlXeV/duirZZrXbN5DSejM4pZTX+yJUwu3+rC1swyyk01mY6JIHiiXM="
    skip_cleanup: true
    message: "deployed to DEV"
    on:
      branch: "master"